### ISSUE TITLE
Not compatible with react-native-device-info

### ISSUE THREAD

**Issue by Amurmurmur** [react-community/react-native-maps#1028]
Once installed react-native-device-info and having react-native-maps v0.13
Throws 
```
Caused by java.lang.NoClassDefFoundError
com.airbnb.android.react.maps.AirMapManager.<init> (AirMapManager.java:54)
```
However changing:

```
dependencies {
  compile "com.facebook.react:react-native:+"
  compile "com.google.android.gms:play-services-base:9.8.0"
  compile "com.google.android.gms:play-services-maps:9.8.0"
}
```
to

```
dependencies {
  compile "com.facebook.react:react-native:+"
  compile "com.google.android.gms:play-services-base:+"
  compile "com.google.android.gms:play-services-maps:+"
}
```
in react-native-maps build.gradle

or adding:
```
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-location:+'
    compile 'com.google.android.gms:play-services-maps:+'
```
to app/build.gradle

Fixes the issue. I guess the build.gradle should be updated for that package, since upgrading to newer versions in the future will replace build.gradle script and the fix will have to be applied again, obviously.
Or adding above lines to your app build.gradle should be doumented as a fix somewhere in Readme for this package.

**Comment by mlanter** [comment]
If you add something like this to your project's `build.gradle` it will fix it without any changes to the library.  This overrides what is specified in any libraries (such as `react-native-maps` or `react-native-device-info`) with the version here.

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('9.8.0')
        }
    }
}

dependencies {
    compile project(':react-native-maps')
    ...
}
```

**Comment by esutton** [comment]
Using MapView 0.13.1  I get  following crash:

**at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)**

adb logcat
```
--------- beginning of main
03-27 15:04:41.644  8619  8648 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
03-27 15:04:54.194  8619  8648 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
03-27 15:04:54.203  8619  8619 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-27 15:04:54.203  8619  8619 E AndroidRuntime: FATAL EXCEPTION: main
03-27 15:04:54.203  8619  8619 E AndroidRuntime: Process: com.fieldscout, PID: 8619
03-27 15:04:54.203  8619  8619 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zze)"
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:149)
03-27 15:04:54.203  8619  8619 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:892)
```

```
    "react": "~15.4.1",
    "react-native": "0.42.3",
    "react-native-maps": "^0.13.1",
    "react-native-device-info": "^0.10.1",
```

[react-native-device-info/android/build.gradle](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle)

I do not understand the consequences of play-services.  What is recommended best work-around?

**Comment by KarlosQ** [comment]
If you change your react-native-device-info/android/build.gradle

dependencies {
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-gcm:10.0.1'
}

The react-native run-android works fine.

My problem is if I put 10.0.1 version later the app in the emulator show me:

![screen shot 2017-04-04 at 21 32 22](https://cloud.githubusercontent.com/assets/15233913/24675099/3ae65504-197e-11e7-9314-76488160267e.png)

My Google Repository (46) is full update and with react-native-maps 0.13.0 and gsm 9.8.0 works fine. 

Which is the solution?

**Comment by alvelig** [comment]
Use 10.2 or the latest. 
See https://github.com/react-community/react-native-maps/issues/1773#issuecomment-351122033
