### ISSUE TITLE
error when trying to run app

### ISSUE THREAD

**Issue by cinder92** [react-community/react-native-maps#1059]
Hello i just want to run my app with this plugin and simple i can't :(, i always receive this error

```
java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:53)
                                                       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                       at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:206)
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:71)
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:145)
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:142)
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
                                                       at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:958)
                                                       at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:863)
                                                       at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
                                                       at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
                                                       at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:818) 
```

any suggestions?

**Comment by rborn** [comment]
@cinder92 maybe this helps? https://github.com/airbnb/react-native-maps/issues/818

**Comment by cinder92** [comment]
@rborn  yep it works! thanks a lot
