### ISSUE TITLE
java lang NullPointerException at com.airbnb.android.react.maps.AirMapManager.receiveCommand

### ISSUE THREAD

**Issue by huangkaiw3n** [react-community/react-native-maps#1372]
react-native: "0.44.0"
react-native-maps: "0.15.2"

I'm getting this error randomly on a small portion of my users. It happens occasionally for me when the map loads but it's been rather inconsistent and hard to replicate so far.

```
java.lang.NullPointerException: 
  at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:195)
  at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:29)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:703)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:261)
  at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:787)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:843)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:889)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
  at android.view.Choreographer.doCallbacks(Choreographer.java:695)
  at android.view.Choreographer.doFrame(Choreographer.java:628)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7229)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Anyone with a similar issue or can help?

**Comment by foyarash** [comment]
This seems to happen when an animateToRegion occurs.

How do you call this function?

**Comment by huangkaiw3n** [comment]
I'm calling `animateToRegion` once I receive props of the user's current location. Anything specific I need to avoid in using `animateToRegion`?

```
componentWillReceiveProps(newProps) {
    // Delay animations as they do not react if launched before map is fully loaded
    // Could be due to map not ready etc.
    if (this.refs["MAP"] && newProps.currentLocation !== this.props.currentLocation) {
      console.log('animate to current')
      setTimeout(() => {
        if (this.refs["MAP"]) {
          this.refs["MAP"].animateToRegion(newRegion(newProps.currentLocation), 1000)
        }
      }, 1000);
    }
}
```

**Comment by foyarash** [comment]
I use geolocation too in my project, when i have the user's geolocation i just put the geolocation data in my state, and use this data with the region/initialRegion prop. But maybe you are doing it the right way.

Does your newRegion returns the latitude/longitude delta, as mentioned in the doc?

**Comment by huangkaiw3n** [comment]
Yup, it returns a region object as specified in docs: 
```
type Region {
  latitude: Number,
  longitude: Number,
  latitudeDelta: Number,
  longitudeDelta: Number,
}
```

So I get some app crash reports occasionally and wondering how I can fix it. By the way, how do you know from my error log that it's due to `animateToRegion`? I couldn't tell which method was causing it from the log

**Comment by foyarash** [comment]
I just looked at the AirMapManager.java at the correct line, and it refers to the animateToRegion call

**Comment by huangkaiw3n** [comment]
Ah I see, thanks. However, I still can't figure out exactly why the error is thrown as region is passed correctly

**Comment by foyarash** [comment]
I would advise you to use the region/initialRegion property instead of animateToRegion method.

**Comment by alvelig** [comment]
@foyarash to the contrary. Use animate to region. Just update to the latest. See #209.

This is fixed already.
