### ISSUE TITLE
Crash on 4.4.4 tablet

### ISSUE THREAD

**Issue by IgorVanian** [react-community/react-native-maps#1389]
Running on SM-T560 tablet (4.4.4)
First time the app asked me to update google play services. Now it's 10.2.98 and crashes on map load.

RN 44
RNM 12.4/15.2 (both not working)

```
E/AndroidRuntime(18705): java.lang.NullPointerException
E/AndroidRuntime(18705): 	at android.os.Parcel.readException(Parcel.java:1478)
E/AndroidRuntime(18705): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(18705): 	at xw.a(:com.google.android.gms.DynamiteModulesB:1259)
E/AndroidRuntime(18705): 	at xi.a(:com.google.android.gms.DynamiteModulesB:3105)
E/AndroidRuntime(18705): 	at ns.b(:com.google.android.gms.DynamiteModulesB:142)
E/AndroidRuntime(18705): 	at oq.a(:com.google.android.gms.DynamiteModulesB:1163)
E/AndroidRuntime(18705): 	at pk.a(:com.google.android.gms.DynamiteModulesB:258)
E/AndroidRuntime(18705): 	at pf.a(:com.google.android.gms.DynamiteModulesB:331)
E/AndroidRuntime(18705): 	at xh.a(:com.google.android.gms.DynamiteModulesB:85)
E/AndroidRuntime(18705): 	at com.google.maps.api.android.lib6.impl.cn.a(:com.google.android.gms.DynamiteModulesB:120)
E/AndroidRuntime(18705): 	at pf.a(:com.google.android.gms.DynamiteModulesB:9199)
E/AndroidRuntime(18705): 	at ot.g(:com.google.android.gms.DynamiteModulesB:491)
E/AndroidRuntime(18705): 	at ot.a(:com.google.android.gms.DynamiteModulesB:426)
E/AndroidRuntime(18705): 	at pk.a(:com.google.android.gms.DynamiteModulesB:440)
E/AndroidRuntime(18705): 	at od.a(:com.google.android.gms.DynamiteModulesB:34)
E/AndroidRuntime(18705): 	at se.a(:com.google.android.gms.DynamiteModulesB:231)
E/AndroidRuntime(18705): 	at rt.a(:com.google.android.gms.DynamiteModulesB:788)
E/AndroidRuntime(18705): 	at rk.a(:com.google.android.gms.DynamiteModulesB:1837)
E/AndroidRuntime(18705): 	at rn.handleMessage(:com.google.android.gms.DynamiteModulesB:4345)
E/AndroidRuntime(18705): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18705): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(18705): 	at android.app.ActivityThread.main(ActivityThread.java:5590)
E/AndroidRuntime(18705): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18705): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(18705): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
E/AndroidRuntime(18705): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
E/AndroidRuntime(18705): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by vnhnhm** [comment]
Same here:

```javascript
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-maps": "^0.15.2",
```

**Comment by henrikra** [comment]
We got the same with Samsung SM-N910F
Here is the log:
```
java.lang.SecurityException Unknown calling package name 'com.wolt.courierapp'. 
    Parcel.java:1620 android.os.Parcel.readException
    Parcel.java:1573 android.os.Parcel.readException
    :com.google.android.gms.DynamiteModulesB:8 pi.a
    :com.google.android.gms.DynamiteModulesB:162 ny.a
    :com.google.android.gms.DynamiteModulesB:29 lu.a
    :com.google.android.gms.DynamiteModulesB:10 ly.run
    Executors.java:423 java.util.concurrent.Executors$RunnableAdapter.call
    FutureTask.java:237 java.util.concurrent.FutureTask.run
    ThreadPoolExecutor.java:1113 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:588 java.util.concurrent.ThreadPoolExecutor$Worker.run
    :com.google.android.gms.DynamiteModulesB:6 qo.run
    Thread.java:818 java.lang.Thread.run
```

**Comment by alvelig** [comment]
app/build.gradle file:
```
compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
}
compile 'com.google.android.gms:play-services-base:11.+'
compile 'com.google.android.gms:play-services-maps:11.+'
```
would help?

**Comment by alvelig** [comment]
Refers #1773

**Comment by alvelig** [comment]
Will merge this issue to #1773
