### ISSUE TITLE
Error while Testing on [ANDROID]

### ISSUE THREAD

**Issue by cinder92** [react-community/react-native-maps#1558]
hello i receive this error while trying to print the map

```
08-15 22:49:03.550 31083-31083/com.elevmech.chndeliveryservice E/UncaughtException: java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo)"
                                                                                        at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                                                        at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                                                                                        at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                                                                                        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:129)
                                                                                        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
                                                                                        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
                                                                                        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                                                        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                                                        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
                                                                                        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
                                                                                        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
                                                                                        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                                        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                                                                        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:882)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
                                                                                        at android.os.Handler.handleCallback(Handler.java:743)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:150)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
08-15 22:49:03.840 31083-31083/com.elevmech.chndeliveryservice E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.elevmech.chndeliveryservice, PID: 31083
                                                                                 java.lang.AbstractMethodError: abstract method "void com.google.android.gms.dynamic.zza.zza(com.google.android.gms.dynamic.zzo)"
                                                                                     at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                                                     at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                                                                                     at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                                                                                     at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:129)
                                                                                     at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
                                                                                     at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
                                                                                     at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
                                                                                     at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
                                                                                     at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
                                                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
                                                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
                                                                                     at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                                     at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                                                                     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:882)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
                                                                                     at android.os.Handler.handleCallback(Handler.java:743)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

```

build.gradle

```
dependencies {
    compile project(':react-native-push-notification')
    compile project(':react-native-maps')
    compile project(':react-native-firebase')
    compile project(':react-native-image-picker')
    compile project(':react-native-interactable')
    compile project(':react-native-vector-icons')
    compile project(':react-native-linear-gradient')
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms"
    }
    compile ('com.google.android.gms:play-services-gcm:11.0.0') {
        force = true;
    }

    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    
}
```

RN Version : 0.44.0
RNMaps Version : 0.16.1
OS : Mac Os Sierra

Any idea?

**Comment by krizka** [comment]
I had this crash while some libraries was building with different gms library versions. All become fine, when I fixed all the versions in node_modules.

**Comment by foyarash** [comment]
Try this in your build.gradle

`
compile(project(':react-native-maps')) {
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
 }`

**Comment by bintoll** [comment]
I have the same issue, i tried:
this:
`compile project(':react-native-maps')`
and this:
`compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'`
in `app/build.gradle` dependencies
The app works but crashes whan i open scene with map.
I also tried @foyarash solution but my app did not start at all with this error:
`12:24:11.478 23382-23408/com.betclub E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                             Process: com.betclub, PID: 23382
                                                             java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
                                                                 at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52)
                                                                 at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                                 at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711)
                                                                 at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218)
                                                                 at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74)
                                                                 at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151)
                                                                 at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148)
                                                                 at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
                                                                 at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:97)
                                                                 at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950)
                                                                 at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880)
                                                                 at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104)
                                                                 at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218)
                                                                 at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.maps.GoogleMapOptions" on path: DexPathList[[zip file "/data/app/com.betclub-1/base.apk"],nativeLibraryDirectories=[/data/app/com.betclub-1/lib/x86, /data/app/com.betclub-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                 at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:52) 
                                                                 at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                                 at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711) 
                                                                 at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218) 
                                                                 at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74) 
                                                                 at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151) 
                                                                 at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148) 
                                                                 at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76) 
                                                                 at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:97) 
                                                                 at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950) 
                                                                 at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880) 
                                                                 at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104) 
                                                                 at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218) 
                                                                 at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197) 
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                             	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
                                                                 at java.lang.Class.classForName(Native Method)
                                                                 at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                 at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                 		... 20 more
                                                              Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-18 12:24:11.727 23382-23403/com.betclub E/Surface: getSlotFromBufferLocked: unknown buffer: 0xe0a023c0`

Hope that the issue will be solved. Thanks!

**Comment by alvelig** [comment]
see #1773
