### ISSUE TITLE
crash on animateToLocation

### ISSUE THREAD

**Issue by ataomega** [react-community/react-native-maps#1868]
App crashes when you try to animate on map
```
12-11 15:15:56.792 7473-7473/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.appname.android.client, PID: 7473
                                                 com.facebook.react.bridge.NoSuchKeyException: couldn't find key longitudeDelta in dynamic object
                                                     at com.facebook.react.bridge.ReadableNativeMap.getDouble(Native Method)
                                                     at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:215)
                                                     at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:27)
                                                     at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:703)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:261)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:787)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:843)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:48)
                                                     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:889)
                                                     at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                     at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                                     at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:957)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by alvelig** [comment]
There's no such method `animateToLocation`. https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md#methods

As far as I see, you are using `animateToRegion`, and don't pass correct Region object (`couldn't find key longitudeDelta in dynamic object`). See docs.
