### ISSUE TITLE
 "export 'default' (imported as 'MapView') was not found in './lib/components/MapView'

### ISSUE THREAD

**Issue by hedgepigdaniel** [react-community/react-native-maps#1970]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react-native-maps": "0.19.0",
"react-native": "0.52.0",
"haul": "1.0.0-beta.12",
"webpack" : "3.8.1",
"babel-code": "6.26.0",
"babel-plugin-transform-class-properties": "6.24.1",
"babel-plugin-transform-flow-strip-types": "6.22.0",
"babel-plugin-transform-object-rest-spread": "6.26.0",
"babel-preset-env": "1.6.1",
"babel-preset-react": "6.24.1",

#### To start haul/webpack and compile the JS ####
1. Check out the test repository and switch to the `master` branch:
2. Run `yarn` to install dependencies
4. Run `yarn run haul` to run haul, which compiles the JS. Select Android as the platform.

#### To test the app on a device ####
1. Connect an android device via ADB
2. Run `yarn run run-android` to compile, install, and run the native app on the device
3. Shake the phone, go to "Dev Settings", and disable "Delta Bundles", then reload

#### To see the bug ####
1. Checkout the `master` branch. Notice that the app does not compile. This is the issue.
2. To explain my desire to reconfigure babel in a manner that causes this issue, checkout the `workaround` branch, where I patch `webhack.haul.js` to apply a different babel config just for react-native-maps so that I can avoid the issue. Notice that in the `yarn run haul` process which runs webpack, there is a big obvious warning about the fact that my code imports a named export which does not exist. In my experience this makes development much faster by catching mistakes earlier in development. In the `fix-import` branch there is a fix for the error in my app, which would otherwise have become an runtime error which may or may not have cause a crash or some other hard to trace, incorrect behaviour at some point during use.

The error I hope to see when I import an undefined export looks as follows (reproduce on the `workaround` branch):
```
 ERROR  Failed to compile.

./App.js
37:10-24 "export 'NONEXISTENT_EXPORT' (imported as 'IMPORTED_VALUE') was not found in './helper.js'
   at HarmonyImportSpecifierDependency._getErrors (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
   at HarmonyImportSpecifierDependency.getErrors (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:44:16)
   at Compilation.reportDependencyErrorsAndWarnings (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:712:22)
   at Compilation.finish (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:561:9)
   at applyPluginsParallel.err (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compiler.js:506:17)
   at /home/daniel/flattenedmonad/RNMExportBug/node_modules/tapable/lib/Tapable.js:289:11
   at _addModuleChain (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:507:11)
   at processModuleDependencies.err (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:477:14)
   at process._tickCallback (internal/process/next_tick.js:150:11)
@ ./App.js
@ ./index.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js
```

### Expected Behavior

The code should compile successfully

### Actual Behavior

The compile error on the `master` branch looks like this:
```
./node_modules/react-native-maps/index.js
3:17-24 "export 'default' (imported as 'MapView') was not found in './lib/components/MapView'
   at HarmonyImportSpecifierDependency._getErrors (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
   at HarmonyImportSpecifierDependency.getErrors (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:44:16)
   at Compilation.reportDependencyErrorsAndWarnings (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:712:22)
   at Compilation.finish (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:561:9)
   at applyPluginsParallel.err (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compiler.js:506:17)
   at /home/daniel/flattenedmonad/RNMExportBug/node_modules/tapable/lib/Tapable.js:289:11
   at _addModuleChain (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:507:11)
   at processModuleDependencies.err (/home/daniel/flattenedmonad/RNMExportBug/node_modules/webpack/lib/Compilation.js:477:14)
   at process._tickCallback (internal/process/next_tick.js:150:11)
@ ./node_modules/react-native-maps/index.js
@ ./App.js
@ ./index.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.js
```

There is one such error for various other modules within `react-native-maps` that are imported.

The cause of the issue seems to be that the files contain commonjs exports like 
```
module.exports = ...;
```
instead of the standard es6
```
export default ...;
```
I'm not sure if there is a reason why this is the case - it seems confusing to me considering the same files have es6 imports and other syntax.

### Reproducible Demo

https://github.com/hedgepigdaniel/RNMExportBug

**Comment by rborn** [comment]
@hedgepigdaniel is this happening without haul? 
I agree thought that the exports maybe should be converted to ES6. 
Mind a PR?

**Comment by hedgepigdaniel** [comment]
I don't think so. It works fine with Expo for example.

Cool, I'll make a PR :)

**Comment by rborn** [comment]
@hedgepigdaniel great, but please check for all the examples to run ok. Thanks!

**Comment by alvelig** [comment]
LOL https://github.com/59naga/babel-plugin-add-module-exports
Looks like it's a haul missing some babel configs.
But I agree, let's go ES6

**Comment by hedgepigdaniel** [comment]
I think that babel plugin is doing somethng different - the `module.exports = ...'` line that it adds is the same one that doesn't work in this case.

The requirement for getting the warning for an undefined import from webpack is that babel doesn't transpile the es6 exports at all - i.e. that babel leaves things like `export default blah;`, `export const thing;` and `import { thing } from 'file.js';` exactly as they are, without inserting any commonjs imports and exports like `module.eports = blah'; `exports.thing = thing;`, or `require('file.js')`

**Comment by rborn** [comment]
@hedgepigdaniel #1982 is merged, can this be closed? 😊

**Comment by hedgepigdaniel** [comment]
Yep, thanks :)
