### ISSUE TITLE
when set showsUserLocation true app crashes

### ISSUE THREAD

**Issue by Xaus** [react-community/react-native-maps#2169]
### Is this a bug report?
     yes
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
     yes
### Environment
    react-native: 0.54.4
    react: 16.3.0-alpha.1
    react-native-maps: 0.21.0
### Steps to Reproduce
1 - install react native 0.54.4 and react native maps 0.21.0 by instructions and set api key. 
2 - using this code for map : 
`        <MapView
  style={styles.map}
  ref={ref => this.map = ref}
  showsUserLocation={true}
  followUserLocation={false}
  showsMyLocationButton={false}
  showsTraffic= {true}
  minZoomLevel = {13}
  provider={PROVIDER_GOOGLE}

  >
</MapView>
`

3 - using this for styles : 
`
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },map: {
          ...StyleSheet.absoluteFillObject,
  },
});

`
4 - react-native run-android 

5 - when map loads , app crashes

### Expected Behavior
see the map and see my location with a blue indicator
### Actual Behavior
on map load , app crashes 
----------
when i set   showsUserLocation={false} everything works fine
---------
---------
when I edit this file : 
lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java

`coordinate.putBoolean("isFromMockProvider", location.isFromMockProvider()); `
to 
`coordinate.putBoolean("isFromMockProvider", false); `

every thing works fine
--------
@deorukhkarchaitanya

**Comment by deorukhkarchaitanya** [comment]
Hi @Xaus. I'll look into it and get back to you as soon as I can. I think you already found a solution to fix your crash. Thanks for reporting.

**Comment by deorukhkarchaitanya** [comment]
I tested the code on API 27 and API 25 (Simulator as well as a real device). Did not face any crashes on either. Can you post a logcat of your crash?

![screen shot 2018-04-09 at 2 12 45 pm](https://user-images.githubusercontent.com/24487274/38488352-d1ea5e5a-3c00-11e8-9d16-58209cca73d2.png)
![screen shot 2018-04-09 at 2 13 57 pm](https://user-images.githubusercontent.com/24487274/38488353-d21251b2-3c00-11e8-82e9-8654c4ff331e.png)

**Comment by Xaus** [comment]
04-09 13:59:50.904 21177-21177/com.owraman.taxitimedriver D/SurfaceTexture:     EGLImage: dpy=0x1, img=0x10000001
04-09 13:59:50.931 21177-21177/com.owraman.taxitimedriver D/dalvikvm: create interp thread : stack size=128KB
04-09 13:59:50.931 21177-21177/com.owraman.taxitimedriver D/dalvikvm: create new thread
04-09 13:59:50.932 21177-21177/com.owraman.taxitimedriver D/dalvikvm: new thread created
04-09 13:59:50.932 21177-21177/com.owraman.taxitimedriver D/dalvikvm: update thread list
04-09 13:59:50.932 21177-21298/com.owraman.taxitimedriver D/dalvikvm: threadid=61: interp stack at 0x5ff9a000
04-09 13:59:50.932 21177-21298/com.owraman.taxitimedriver D/dalvikvm: threadid=61: created from interp
04-09 13:59:50.932 21177-21177/com.owraman.taxitimedriver D/dalvikvm: start new thread
04-09 13:59:50.932 21177-21298/com.owraman.taxitimedriver D/dalvikvm: threadid=61: notify debugger
04-09 13:59:50.932 21177-21298/com.owraman.taxitimedriver D/dalvikvm: threadid=61 (GAC_Executor[1]): calling run()
04-09 13:59:50.995 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) new GraphicBuffer needed
04-09 13:59:50.995 21177-21276/com.owraman.taxitimedriver D/BufferQueue:     [OLD] gb:NULL
04-09 13:59:50.999 21177-21276/com.owraman.taxitimedriver D/GraphicBuffer: create handle(0x5d100500) (w:544, h:922, f:2)
04-09 13:59:51.003 21177-21177/com.owraman.taxitimedriver I/SurfaceTexture: [unnamed-21177-0](this:0x600fc0d0,api:1) [void* android::SurfaceTexture::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&)]
04-09 13:59:51.003 21177-21177/com.owraman.taxitimedriver D/SurfaceTexture:     GraphicBuffer: gb=0x5d0f58e8 handle=0x5d0ee6d8
04-09 13:59:51.003 21177-21177/com.owraman.taxitimedriver D/SurfaceTexture:     EGLImage: dpy=0x1, img=0x10000002
04-09 13:59:51.004 21177-21276/com.owraman.taxitimedriver I/BufferQueue:     [NEW] gb=0x5d0fe520, handle=0x5d100500, w=540, h=922, s=544, fmt=2
04-09 13:59:51.016 21177-21177/com.owraman.taxitimedriver D/AndroidRuntime: Shutting down VM
04-09 13:59:51.016 21177-21177/com.owraman.taxitimedriver W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x413319a8)
04-09 13:59:51.016 21177-21177/com.owraman.taxitimedriver W/dalvikvm: threadid=1: uncaught exception occurred
04-09 13:59:51.023 21177-21177/com.owraman.taxitimedriver W/System.err: java.lang.NoSuchMethodError: android.location.Location.isFromMockProvider
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.airbnb.android.react.maps.AirMapView$3.onMyLocationChange(AirMapView.java:199)
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.android.gms.maps.zzh.zzF(Unknown Source)
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.android.gms.maps.internal.zzay.onTransact(Unknown Source)
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at android.os.Binder.transact(Binder.java:310)
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at fj.b(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):20)
04-09 13:59:51.026 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.android.gms.maps.internal.bo.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):5)
04-09 13:59:51.027 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.maps.api.android.lib6.impl.dg.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):41)
04-09 13:59:51.027 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.maps.api.android.lib6.impl.dg.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):36)
04-09 13:59:51.027 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.google.maps.api.android.lib6.impl.cn.run(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):57)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at android.os.Handler.handleCallback(Handler.java:800)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at android.os.Looper.loop(Looper.java:194)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5433)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:924)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-09 13:59:51.028 21177-21177/com.owraman.taxitimedriver W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
04-09 13:59:51.030 21177-21177/com.owraman.taxitimedriver E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            java.lang.NoSuchMethodError: android.location.Location.isFromMockProvider
                                                                                at com.airbnb.android.react.maps.AirMapView$3.onMyLocationChange(AirMapView.java:199)
                                                                                at com.google.android.gms.maps.zzh.zzF(Unknown Source)
                                                                                at com.google.android.gms.maps.internal.zzay.onTransact(Unknown Source)
                                                                                at android.os.Binder.transact(Binder.java:310)
                                                                                at fj.b(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):20)
                                                                                at com.google.android.gms.maps.internal.bo.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):5)
                                                                                at com.google.maps.api.android.lib6.impl.dg.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):41)
                                                                                at com.google.maps.api.android.lib6.impl.dg.a(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):36)
                                                                                at com.google.maps.api.android.lib6.impl.cn.run(:com.google.android.gms.dynamite_dynamitemodulesb@12521002@12.5.21 (000304-189987672):57)
                                                                                at android.os.Handler.handleCallback(Handler.java:800)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                at android.os.Looper.loop(Looper.java:194)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5433)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:924)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                                                at dalvik.system.NativeStart.main(Native Method)
04-09 13:59:51.062 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) new GraphicBuffer needed
04-09 13:59:51.062 21177-21276/com.owraman.taxitimedriver D/BufferQueue:     [OLD] gb:NULL
04-09 13:59:51.080 21177-21276/com.owraman.taxitimedriver D/GraphicBuffer: create handle(0x5d100a30) (w:544, h:922, f:2)
04-09 13:59:51.083 21177-21276/com.owraman.taxitimedriver I/BufferQueue:     [NEW] gb=0x5d100998, handle=0x5d100a30, w=540, h=922, s=544, fmt=2
04-09 13:59:51.092 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.092 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:3] time:0, handle:0x5d100a30
04-09 13:59:51.092 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:2] time:76954500, handle:0x5d100500
04-09 13:59:51.098 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.098 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:2] time:76954500, handle:0x5d100500
04-09 13:59:51.098 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:3] time:76954531, handle:0x5d100a30
04-09 13:59:51.110 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.110 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:3] time:76954531, handle:0x5d100a30
04-09 13:59:51.110 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:2] time:76954537, handle:0x5d100500
04-09 13:59:51.137 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.137 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:2] time:76954537, handle:0x5d100500
04-09 13:59:51.138 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:3] time:76954549, handle:0x5d100a30
04-09 13:59:51.141 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.141 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:3] time:76954549, handle:0x5d100a30
04-09 13:59:51.141 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:2] time:76954576, handle:0x5d100500
04-09 13:59:51.154 21177-21276/com.owraman.taxitimedriver I/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) [queue] queued:1 (drop frame)
04-09 13:59:51.154 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1) NEW [idx:2] time:76954576, handle:0x5d100500
04-09 13:59:51.154 21177-21276/com.owraman.taxitimedriver D/BufferQueue: [unnamed-21177-0](this:0x62051fe8,api:1)     [idx:3] time:76954580, handle:0x5d100a30
04-09 13:59:51.185 21177-21266/com.owraman.taxitimedriver D/dalvikvm: GC_FOR_ALLOC freed 1171K (16660), 29% free 9727K/13564K, paused 29ms, total 30ms
04-09 13:59:51.193 21177-21254/com.owraman.taxitimedriver D/NativeCrypto: NativeCrypto_EVP_VerifyInit ctx=0x5d103078
04-09 13:59:51.193 21177-21254/com.owraman.taxitimedriver D/NativeCrypto: NativeCrypto_EVP_VerifyInit algorithmChars=RSA-SHA256
04-09 13:59:51.204 21177-21311/com.owraman.taxitimedriver D/dalvikvm: threadid=62: interp stack at 0x61649000
@deorukhkarchaitanya

**Comment by deorukhkarchaitanya** [comment]
Are you sure your API level is 18 or above? isFromMockProvider was added in API 18

**Comment by Xaus** [comment]
Api 17

**Comment by deorukhkarchaitanya** [comment]
API 17 does not support it. I will create a PR in some time to address this issue.

**Comment by deorukhkarchaitanya** [comment]
@Xaus fixed with this PR
Close the issue once you test it
 https://github.com/react-community/react-native-maps/pull/2172

**Comment by rborn** [comment]
@deorukhkarchaitanya merged, @Xaus please test with the last git version and let us know.
Thank you 🤗

**Comment by pitchourou** [comment]
API level of what ?

**Comment by TusharGuptaAdinav** [comment]
When i am giving the coordinates to the marker it is getting crashed,But working fine in devmode.

**Comment by TusharGuptaAdinav** [comment]
I tried each and everything mentioned here,But did not worked.The App is getting crashed only after creating apk when i am running on real device.
