### ISSUE TITLE
[Android] Multiple dex files define Lbolts/AggregateException

### ISSUE THREAD

**Issue by mkhuda** [react-community/react-native-maps#2300]
### Is this a bug report?

Yes, or perhaps any configuration errors on my project

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.55.4
    react: 16.3.1
    react-native-maps: 0.21.0
  
    Target Platform: Android 6.0.1/Xiaomi
    Operating System: Ubuntu 16.04

### Steps to Reproduce

1. `cd android`
2. `./gradlew clean`
3. `cd ..` and run `react-native run-android --variant=release`

This is what happened:
```bash
> Task :app:bundleReleaseJsAndAssets
....
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lbolts/AggregateException;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:506)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:336)
        at com.android.dx.command.dexer.Main.runDx(Main.java:291)
        at com.android.dx.command.dexer.Main.main(Main.java:247)
        at com.android.dx.command.Main.main(Main.java:94)

```
But if I remove the react-native-camera package, build release works fine.

### Expected Behavior

Build with variant release should work, but there may be any mistakes on my project configuration.

### Actual Behavior

Project successfully runs maps on debug version `react-native run-android`. But there was a build error in the release variant `react-native run-android --variant=release`.

### Reproducible Demo

Here are some of my configuration:
- on `android/app/build.gradle` dependencies section:
```gradle
dependencies {
    compile (project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
      }
    compile (project(':react-native-camera')) {
        exclude group: "com.android.support"
        compile 'com.android.support:exifinterface:27.+'
        compile ('com.google.android.gms:play-services-vision:11.0.0') {
            force = true
        }
      }
    compile "com.android.support:appcompat-v7:26.0.2"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-geolocation-service')
    compile ("com.google.android.gms:play-services-base:11.0.0") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-maps:11.0.0") {
        force = true;
    }
    compile ("com.google.android.gms:play-services-basement:11.0.0") {
        force = true;
    }
    compile fileTree(dir: "libs", include: ["*.jar"])
}

```
- on `android/settings.gradle`:
```gradle
rootProject.name = 'myapp'
include ':react-native-camera'
project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera/android')

include ':app'

include ':react-native-geolocation-service'
project(':react-native-geolocation-service').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-geolocation-service/android')

include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```
- on `android/build.gradle`:
```gradle
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}
```
Is there an error in my configuration? Thank you very much.

**Comment by mkhuda** [comment]
Reinstalling react-native-maps and changed some configuration on app `build.gradle` fixed my problem

- My final **app:build.gradle**
```gradle

....
/* Enabling ProguardInReleaseBuilds */
def enableProguardInReleaseBuilds = true
....
dependencies {
    compile (project(':react-native-camera')) {
      exclude group: "com.android.support"
      exclude group: "com.google.android.gms"
      compile 'com.android.support:exifinterface:27.+'
      compile ('com.google.android.gms:play-services-vision:12.0.1') {
          force = true
      }
    }

    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:12.0.1'
    compile 'com.google.android.gms:play-services-maps:12.0.1'

    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile fileTree(dir: "libs", include: ["*.jar"])
}
```
