### ISSUE TITLE
Having continuous build error with aapt in fresh created project

### ISSUE THREAD

**Issue by santanu4ver** [react-community/react-native-maps#2399]
### Is this a bug report?
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?
Yes and followed

### Environment

macOS platform: El Capitan 10.11.6
package.json:

```
{
  "name": "navigationApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-navigation": "^1.1.478"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.4.1",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### Steps to Reproduce

- Created a fresh app by `react-native init navigationApp`
- Following the installation [guide](https://wix.github.io/react-native-navigation/#/installation-android), ran `npm install --save react-native-navigation@latest`
- Followed other steps as detailed mentioned int he same instruction page linked above
- Ran `react-native run-android` in the project directory

### Expected Behavior

Project run without an error 

### Actual Behavior

Running as Android thrown following error:
![image](https://user-images.githubusercontent.com/1856278/43258742-68e154fe-90f1-11e8-8110-2dab8a028b9d.png)

Moved to android folder in Terminal and ran `./gradlew clean`, that successfully completed.

Ran `./gradlew assembleDebug --stacktrace` in the same location, thrown a large error, following are excerpts from it:

```
at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:201)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:82)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more
Caused by: com.android.ide.common.process.ProcessException: Failed to execute aapt
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:867)
        at com.android.build.gradle.tasks.ProcessAndroidResources.doFullTaskAction(ProcessAndroidResources.java:194)
        ... 82 more
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process /Users/santanu/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/santanu/Library/Android/sdk/platforms/android-25/android.jar -M /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/manifests/aapt/release/AndroidManifest.xml -S /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/res/merged/release -m -J /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/generated/source/r/release --custom-package com.reactnativenavigation --non-constant-id -0 apk --output-text-symbols /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/bundles/default --no-version-vectors}
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:865)
        ... 83 more
Caused by: com.android.ide.common.process.ProcessException: Error while executing process /Users/santanu/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/santanu/Library/Android/sdk/platforms/android-25/android.jar -M /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/manifests/aapt/release/AndroidManifest.xml -S /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/res/merged/release -m -J /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/generated/source/r/release --custom-package com.reactnativenavigation --non-constant-id -0 apk --output-text-symbols /Users/santanu/Documents/React Native/navigationApp/node_modules/react-native-navigation/android/app/build/intermediates/bundles/default --no-version-vectors}
        at com.android.build.gradle.internal.process.GradleProcessResult.buildProcessException(GradleProcessResult.java:74)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:49)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:78)
        at com.android.builder.internal.aapt.AbstractProcessExecutionAapt$1.onSuccess(AbstractProcessExecutionAapt.java:74)
        at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:53)
        at com.android.build.gradle.internal.process.GradleProcessExecutor$1.run(GradleProcessExecutor.java:60)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Users/santanu/Library/Android/sdk/build-tools/26.0.2/aapt'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:369)
        at com.android.build.gradle.internal.process.GradleProcessResult.assertNormalExitValue(GradleProcessResult.java:47)
        ... 9 more


BUILD FAILED

Total time: 2.182 secs
```

### Reproducible Demo

[navigationApp.zip](https://github.com/react-community/react-native-maps/files/2231665/navigationApp.zip)

**Comment by santanu4ver** [comment]
Created in wrong repository.
