### ISSUE TITLE
play-services-base Version collision with react-native-firebase

### ISSUE THREAD

**Issue by vikrantnegi** [react-community/react-native-maps#2418]
### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.56.0
react: 16.4.1
react-native-maps: 0.21.0

  

### Steps to Reproduce
1. Install react native maps
2. Trying to install react-native-firebase

### Expected Behavior
Project should successfully compile

### Actual Behavior
Error: 
`The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 10.2.4. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
`

React native firebase is using 
`implementation ("com.google.android.gms:play-services-base:15.0.1")` 

and reac-native-maps using 
`implementation ('com.google.android.gms:play-services-maps:10.0.1')` 

which is stopping it from compiling.

Any help?

**Comment by jampueroc** [comment]
See edit 2 on [issue comment of react-native-firebase](https://github.com/invertase/react-native-firebase/issues/1155#issuecomment-403226083)

I hope that in next version would fix this 😫

**Comment by vikrantnegi** [comment]
@jampueroc It works but now my app crashes as soon as it loads up. Any idea why?

**Comment by jampueroc** [comment]
@vikrantnegi 

What kind of error you have?

You can try closing all react-native tabs and running again

**Comment by mowbell** [comment]
@jampueroc @vikrantnegi

I suggest you first to check ti 
https://github.com/invertase/react-native-firebase/issues/1155#issuecomment-410886346
And verify your `graddle.properties`, remove it:
org.gradle.configureondemand=true
Taken of:
https://proandroiddev.com/bundling-react-native-during-android-release-builds-ec52c24e200d
It works for me

**Comment by vikrantnegi** [comment]
@jampueroc  I'm getting an error in Logcat:

I think this is because it forces google maps to use google play services version of 15.0.1 and google maps uses google play services version of 10.0.1 and works normally.

```
08-16 10:27:28.997 30875-30902/? E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.arttiee_reactnative, PID: 30875
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:55)
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
        at java.lang.Thread.run(Thread.java:760)
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:55) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916) 
        at java.lang.Thread.run(Thread.java:760) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:55) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916) 
        at java.lang.Thread.run(Thread.java:760) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.arttiee_reactnative-1/base.apk"],nativeLibraryDirectories=[/data/app/com.arttiee_reactnative-1/lib/arm, /data/app/com.arttiee_reactnative-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:55) 
        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173) 
        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130) 
        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127) 
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1175) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1145) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1086) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:116) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916) 
        at java.lang.Thread.run(Thread.java:760) 
08-16 10:27:29.007 30875-30875/? W/unknown:ReactNative: Packager connection already open, nooping.
```

**Comment by mowbell** [comment]
@vikrantnegi Did you have checked https://github.com/invertase/react-native-firebase/issues/1155#issuecomment-410886346
I suggest you check if you have react-native-maps v0.21.0

I share you my gradle code lines `/build.gradle`:
```
dependencies {
        ...
        classpath 'com.google.gms:google-services:4.0.1'
}

ext {
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "27.1.1"
    googlePlayServicesVersion = "15.0.1"
}
```

In `app/build.gradle`

```
dependencies {
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
  ...
  implementation "com.google.android.gms:play-services-base:15.0.1"
  implementation "com.google.android.gms:play-services-maps:15.0.0"
```

I expect it helps you

**Comment by vikrantnegi** [comment]
@mowbell thanks. It is helpful.

**Comment by niranjanbprajapati** [comment]
@vikrantnegi thanks for the solution you provided, i tried it worked the app is running now. But i just wanted to know is this the correct way to solve this issue, telling android to disable version check. also if it will disable version check which version of googleplayserviceplugin will it use to compile it and will it create any issue with react-native-maps and react-native-firebase ?

**Comment by niranjanbprajapati** [comment]
@vikrantnegi Finally found the solution ...StyleSheet.absoluteFillObject is what i needed to add instead of the width and height for style now my code looks like :

```
<View style = {{...StyleSheet.absoluteFillObject}}>				
				<MapView
					provider={PROVIDER_GOOGLE}
					style={{flex: 1}}
					initialRegion={{
						latitude: 18.970780,
						longitude: 72.809780,
						latitudeDelta: 0.0922,
						longitudeDelta: 0.0421
					}}
				/>
			</View>
```

**Comment by niranjanbprajapati** [comment]
Hi @vikrantnegi  Sorry to bother you again. I am not able to compile ios app as its giving me the following error :

> /node_modules/react-native-maps/lib/ios/AirGoogleMaps/RCTConvert+GMSMapViewType.h:10:9: 'GoogleMaps/GoogleMaps.h' file not found

I checked the file is there under GoogleMaps.framework 
I am using non cocopod version for configuration as i can't use pods.

**Comment by vikrantnegi** [comment]
@niranjanbprajapati I've not used maps without pods. Are you also not using firebase without pods?

**Comment by niranjanbprajapati** [comment]
@vikrantnegi yes i am told not to use pods so whatever i am using i am doing without pods and i just now realised that my pushnotifications stopped working it might have happened because of adding `com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
`
can you guide me on fixing that.

**Comment by vikrantnegi** [comment]
@niranjanbprajapati I'm not sure why you have been told to do so, but everything is working fine at my end. I'm using push notifications using firebase and PubNub they are working perfectly fine. 

This might be due to something else.

**Comment by KunwarVSuryavanshi** [comment]
After spending 7 hours i was able to run the app.

For me it worked when
1) I replaced the gradle version to 4.6, i.e
    distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
instead of
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
in the android/gradle/wrapper/gradle.properties
2) Added line,
    com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
in the end of android/app/buildgradle,
