### ISSUE TITLE
Build process failed - :app:dexDebug FAILED

### ISSUE THREAD

**Issue by Dudyboy** [react-community/react-native-maps#378]
I init new react-native project and I wanted to include react-native-maps, but it shows me this error.

``` javascript
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I had to add `/lib` at the end in projectDir in `android/settings.gradle`

``` javascript
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/android/lib')
```

I do not know, what am I doing wrong. I am sure, that problem is in somewhere in react-native-maps module, because it was the last, what I installed from npm and then I wanted to build and it shows me error. 

Dependencies:

``` javascript
"apsl-react-native-button": "^2.5.0",
    "axios": "^0.12.0",
    "buffer": "^4.7.0",
    "install": "^0.8.1",
    "lodash": "^4.13.1",
    "npm": "^3.10.5",
    "react": "15.2.1",
    "react-dom": "^15.2.1",
    "react-motion": "^0.4.4",
    "react-native": "0.29.0",
    "react-native-animatable": "^0.6.1",
    "react-native-button": "^1.6.0",
    "react-native-camera": "github:lwansbrough/react-native-camera",
    "react-native-carousel": "^0.8.0",
    "react-native-dismiss-keyboard": "^1.0.0",
    "react-native-drawer": "^2.2.6",
    "react-native-fit-image": "^1.3.2",
    "react-native-gifted-spinner": "0.0.5",
    "react-native-keyboard-spacer": "^0.3.0",
    "react-native-maps": "^0.7.1",
    "react-native-orientation": "^1.17.0",
    "react-native-responsive-image": "^1.3.0",
    "react-native-router-flux": "^3.31.0",
    "react-native-simple-store": "^1.0.1",
    "react-native-spring-carousel": "^0.3.4",
    "react-native-vector-icons": "^2.0.3",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^5.3.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.1.0"
```

Thanks for help.

**Comment by agumack** [comment]
i have same problem :(

**Comment by texas697** [comment]
not sure why but if you go into android and do a ./gradlew clean it solves the issue

**Comment by sayedatif** [comment]
can you comment your app/build.gradle file? so i can help you . Is your simulator or physical device connected while building app?

**Comment by agumack** [comment]
yep. i solved by: cd android/ && ./gradlew clean && cd .. && react-native run-android

**Comment by magrinj** [comment]
Not working for me, same error... :/

**Comment by Dudyboy** [comment]
I try to reproduce my work. Maybe something will help you identify, what am I doing wrong. (not just me like I see). I build on real device Samsung J5 Android 5.1.1.

```javascript
react-native init test2
cd test2
react-native run-android
adb reverse tcp:8081 tcp:8081
react-native start
```

Everything works well, but this is clean RN0.29. Then

```javascript
npm install --save react-native-maps
sudo rnpm link react-native-maps
```

Then I add Google Maps key to AndroidManifest.xml. Point 4 in installation instructions. Then

```javascript
react-native run-android
```

First false:
```javascript
$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-maps : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

This false was fixed like I wrote in first comment with add /lib at the end in projectDir in android/settings.gradle. Then

```javascript
:app:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I fixed this with texas697 idea, so thumbs up for him.

```javascript
$ ./gradlew clean
:app:clean
:react-native-maps:clean

BUILD SUCCESSFUL

Total time: 1.47 secs
```

Then

```javascript
react-native run-android
adb reverse tcp:8081 tcp:8081
react-native start
```

Build process success, but shows blank view and false in console.

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
    Dimensions
} from 'react-native';
import MapView from 'react-native-maps/components/MapView';

let { width, height } = Dimensions.get('window');

const ASPECT_RATIO = width / height;
const LATITUDE = 37.78825;
const LONGITUDE = -122.4324;
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

class test2 extends Component {
  render() {
    return (
      <View style={styles.container}>
          <MapView
              ref="map"
              style={styles.map}
              initialRegion={{
                  latitude: LATITUDE,
                  longitude: LONGITUDE,
                  latitudeDelta: LATITUDE_DELTA,
                  longitudeDelta: LONGITUDE_DELTA
              }}
          />
      </View>
    );
  }
}

const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-start',
        alignItems: 'center'
    },
    map: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
    }
});

AppRegistry.registerComponent('test2', () => test2);
```

I think somebody wrote about this issue, but not for Android, but IOS. I did not test it on IOS.

![false](https://cloud.githubusercontent.com/assets/20220049/16794501/646b3bfa-48d8-11e6-96d2-1202e25e85ae.png)

Thanks for help.

**Comment by Dudyboy** [comment]
My last console error in previous comment was fixed by [https://github.com/lelandrichardson/react-native-maps/issues/375](url)

Thank you very much everybody.

**Comment by alsh76** [comment]
Same error and ./gradlew clean did not help
```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzpq;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```
"react": "^15.3.2",
"react-native": "^0.33.0",
"react-native-maps": "^0.8.2",

**Comment by ninjz** [comment]
well what i did to get past this was `react-native unlink react-native-maps && react-native link react-native-maps` guess when i linked  withn rnpm previously it didn't do it properly..?

**Comment by minhchu** [comment]
texas's solution works for me

**Comment by crscaballero** [comment]
texas's thanks works fine

**Comment by ujwal-setlur** [comment]
Yes, this worked for me too. 

cd android
./gradlew clean

cd ..
react-native run-android


Any idea why this is?

**Comment by efkan** [comment]
I strongly suspect OS.

I use Elementary OS without a SWAP partition on my SSD.
When the 8 GB ram running out, building process gets stuck at `:app:preDexDebug` and `app:dexDebug` stages. 

In this case probably the building process is `FAILED`.

In short, the problem may be one of OS swap operations, low system resource or both of them.

There are only my observations.

**Comment by dinithminura** [comment]
./gradlew clean not working for me. any other solution?

**Comment by dinithminura** [comment]
./gradlew clean not worked for me 😞  but, 
I remove :react-native-maps from build.gradle and add
...
dependencies {
  ...
  compile 'com.airbnb.android:react-native-maps:0.7.1'
}
This one work for me 🎉 , Thanks for the solution @[yozi-developer](https://github.com/yozi-developer) on #288

**Comment by FauzyAbdan** [comment]
`./gradlew clean` works for me

**Comment by jiteshrai** [comment]
Yes, Its working **cd android/ && ./gradlew clean && cd .. && react-native run-android**
I have solved my problem by above command.

**Comment by ozzyknox** [comment]
Resolved my problem too. Thanks for the help.

**Comment by sibelius** [comment]
try this on build.gradle

```groovy
compile (project(':react-native-maps')) {
        exclude group: "com.google.android.gms"
    }
```

**Comment by kidmysoul** [comment]
all above donot work for me. I solved this when i noticed that i used "com.google.android.gms:play-services-*******" at several places(airbnb use it like  :play-services-maps***** ) and they have multipile version. I changed the version to the same one and my app build worked

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by jabranLmhani** [comment]
I guess the solution is to unlink react-native-maps ( react-native unlink react-native-maps)

**Comment by NithinKulal** [comment]
> ```groovy
> compile (project(':react-native-maps')) {
>         exclude group: "com.google.android.gms"
>     }
> ```

I'm new to react native, Where should I add this..?

**Comment by Darkensses** [comment]
I'm using react-native-maps and my issue was `Execution failed for task ':app:mergeDexDebug'. ` 
I solved by editing the app/build.gradle:

```
android {
    defaultConfig {
        // ...
        multiDexEnabled true
    }
    // ...
}
```

**Comment by AhmedHamedTN** [comment]
open your app in android studio .. let it sychronize gradle and update
`npm start`
`npx react-native run android `
voilà, this worked for me
