### ISSUE TITLE
[rn 0.29.1] Failed to build DependencyGraph: @providesModule naming collision

### ISSUE THREAD

**Issue by maluramichael** [react-community/react-native-maps#428]
I use the cocoapods to install all dependencies. With react-native 0.29.1 the depency graph crashes because react is already installed as a dependency and this module installs its own version of react.

```
project './Camigo.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'

def share_pods

    pod 'Google/SignIn'

    pod 'React', :subspecs => [ 'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTSettings',
    'RCTVibration',
    'RCTLinkingIOS',
    'RCTCameraRoll',
    'RCTPushNotification',
    'RCTGeolocation',
    'RCTCameraRoll',
    'RCTActionSheet' ], :path => '../node_modules/react-native'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'Fabric'
    pod 'Crashlytics'
end

target 'Camigo' do
    share_pods
end

target 'Camigo Staging' do
    share_pods
end
```

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /Users/maluramichael/Development/Work/Camigo/App/node_modules/react-native-maps/node_modules/react/lib/AutoFocusUtils.js collides with /Users/maluramichael/Development/Work/Camigo/App/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: AutoFocusUtils
  Paths: /Users/maluramichael/Development/Work/Camigo/App/node_modules/react-native-maps/node_modules/react/lib/AutoFocusUtils.js collides with /Users/maluramichael/Development/Work/Camigo/App/node_modules/react/lib/AutoFocusUtils.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/maluramichael/Development/Work/Camigo/App/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /Users/maluramichael/Development/Work/Camigo/App/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
```

**Comment by BigPun86** [comment]
+1

**Comment by BigPun86** [comment]
In android, i just remove the node_modules folder inside the react-native-maps directory. But it gets annoying when i have to do this after every npm install

**Comment by rborn** [comment]
Trying to clean the repo, please comment or mention me to re-open the issue if is still the case. Thanks.
