### ISSUE TITLE
Android demo non-functional

### ISSUE THREAD

**Issue by comountainclimber** [react-community/react-native-maps#594]
1.) Clone the repo
2.) cd example
3.) `npm install`
3.) `react-native start`
4.) `react-native run-android`
5.) The app crashes every time I try and run on emulator or physical device...
![screen shot 2016-09-19 at 4 58 37 pm](https://cloud.githubusercontent.com/assets/13072035/18651736/68c8f4fc-7e8a-11e6-8bb7-33530b5e0cd5.png)

No warnings or issues anywhere else other than when I try and open the application...

**Comment by CoreyAR** [comment]
I had the same issue trying to run the example while trouble shooting #585. Haven't found a solution yet.

**Comment by cavilaho** [comment]
Same error here. Running `adb logcat` appear this:
```
09-21 10:51:24.254 31943 31943 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@93d8b3d -- permission denied for this window type
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:595)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:319)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:653)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:397)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-21 10:51:24.254 31943 31943 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by cavilaho** [comment]
Solved. I did two things:
1. **(NOT NECESSARY)** I've added my own Android Key to the `AndroidManifest.xml` file, instead of the one is there.
```xml
<application>
        ....
        <meta-data
          android:name="com.google.android.geo.API_KEY"
          android:value="........................................."/>
</application>
```
2. Give "**Draw over other apps**" permission to `AirMapsExplorer` app. This can be made following this steps ( _tested in Android 6.0.1_ ):
```
1.     Go to the Device Settings
2.     Tap "Apps"
3.     On the top right, tap the gear icon
4.     Under Advanced, chose "Draw over other apps"
5.     Find AirMapsExplorer in the list and tap it
6.     Toggle "Permit drawing over other apps" to on. 
```

The step number 2 worked for me.

**Comment by bbodenmiller** [comment]
@cavilaho unfortunately that solution doesn't appear to work on Android 7.

**Comment by rborn** [comment]
https://github.com/react-community/react-native-maps/pull/1879

**Comment by alvelig** [comment]
@rborn that's android. Let's have this issue for android doc example

**Comment by rborn** [comment]
Docs for running both ios and android example were updated. Closing.
