### ISSUE TITLE
Animate to region crash on Android

### ISSUE THREAD

**Issue by Roconda** [react-community/react-native-maps#701]
Hi

I'm running RN 0.35.0 and RN maps 0.11.0 and I'm getting a null pointer with the following stack trace:

![image](https://cloud.githubusercontent.com/assets/1711132/19443180/34456f18-948c-11e6-9ba8-02f790f7704f.png)

I've created a component which wraps the MapView Component. There is a componentWillUpdate() class with the following code:

``` js
     this.refs.map.animateToRegion({
       latitude: this.props.location.latitude,
       longitude: this.props.location.longitude,
       latitudeDelta: this.state.latitudeDelta,
       longitudeDelta: this.state.longitudeDelta
     })
```

Anyone got a fix for this crash?

Thanks

**Comment by BJChen990** [comment]
Is it possible that the map haven't initialized? I try to call animateToRegion on componentDidMount and got similar answer before.

Maybe if we send the animation request to a pending queue, and process them after map ready?

**Comment by barroslee** [comment]
to check `this.refs.map` is undefined or not?

**Comment by Max9403** [comment]
I had this happen to me as well, I fixed it by doing a null check around the map object, maybe giving a function that returns the state of the map will be enough?

I had it happen doing a request for the users location (which is async on android)

`java.lang.NullPointerException
	at com.airbnb.android.react.maps.AirMapView.animateToCoordinate(AirMapView.java:450)
	at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:206)
	at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:28)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:696)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:257)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:778)
	at android.view.Choreographer.doCallbacks(Choreographer.java:593)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5253)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by Roconda** [comment]
@Max9403 Clever!

I see that you use the animateToCoordinate, which seems to be also broken. Your solution fixes the crashes, but I think it is a temporary solution(could be wrong though).

Hopefully there will be a permanent solution soon..

**Comment by nico1510** [comment]
I'm also using a  component which wraps the MapView and I have some animation logic inside componentDidMount which leads to this error. Currently I'm using a timeout to circumvent this but this is not very safe since there is no way to tell how long map initialization will take. @BJChen990 proposal would be best for my use case.

**Comment by raphkr** [comment]
@Max9403 
Max, in which Java class did u make the change.

**Comment by raphkr** [comment]
This is the error I am getting and though I wrapped the animateToRegion with null check, I keep getting this error:

E/AndroidRuntime(19679): com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'e.refs.map.animateToRegion'), stack:
E/AndroidRuntime(19679): <unknown>@611:5536
E/AndroidRuntime(19679): value@53:3059
E/AndroidRuntime(19679): <unknown>@53:1402
E/AndroidRuntime(19679): d@53:127
E/AndroidRuntime(19679): value@53:1372
E/AndroidRuntime(19679): 
E/AndroidRuntime(19679): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
E/AndroidRuntime(19679): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
E/AndroidRuntime(19679): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19679): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(19679): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
E/AndroidRuntime(19679): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/AndroidRuntime(19679): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime(19679): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(19679): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19679): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(19679): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(19679): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
E/AndroidRuntime(19679): 	at java.lang.Thread.run(Thread.java:841)

**Comment by seppemarotta** [comment]
Has someone solved this ? 
I'm having the same issue
Is there any onMapReady function ?

**Comment by alvelig** [comment]
Use latest version and comment please

**Comment by joelandplus** [comment]
I still get the following crash report:

com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'e.refs.map.animateToRegion'), stack:
<unknown>@439:5802
<unknown>@439:9055
onload@327:467
value@83:1502
value@82:6966
value@82:3508
<unknown>@82:9981
value@44:1343
value@30:2975
<unknown>@30:280
value@30:2426
callFunctionReturnFlushedQueue@30:252

It happens inside navigator.geolocation.watchPosition callback.

**Comment by SvetoslavSlavov** [comment]
Has someone solve this?

**Comment by alvelig** [comment]
@SvetoslavSlavov @joelandplus  if you get `undefined is not an object`, then your map reference is undefined. Use onMapReady to make sure it's ok

**Comment by joelandplus** [comment]
@alvelig I'm already using onMapReady ... but this problem still persists. Worst it i can't seem to reproduce it in all my three Android test devices (5.1, 6.0 & 7.0). But it persists in Android console crash reporting.

**Comment by and951** [comment]
I'm having this problem too. But only on the first run.
I'm getting :  ExceptionsManager.js:65 Cannot read property 'animateToRegion' of null

**Comment by joelandplus** [comment]
This is extremely hard to debug, but i managed to find that MapView ref a.k.a this.map could be null even when called inside onMapReady. Not only that it only randomly happens on some android devices that i couldn't reproduce on my test devices.

**Comment by ashadnasim52** [comment]
> I'm having this problem too. But only on the first run. I'm getting : ExceptionsManager.js:65 Cannot read property 'animateToRegion' of null

This is still happening to me. Did you find any solution?
    "react-native-maps": "^1.8.4",
