### ISSUE TITLE
java.lang.NoSuchMethodError: No static method zzb

### ISSUE THREAD

**Issue by WilliamPeralta** [react-community/react-native-maps#744]
when i open a container with a map my app crash an close:
This is the error in the logcat

```
 Process: com.patento, PID: 12495
                                                             java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.patento-1/base.apk)
                                                                 at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                                                                 at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:60)
                                                                 at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
                                                                 at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                                                                 at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
                                                                 at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                 at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

Can help me? i install and link library , i need modify other? 

Sorry for my bad english

react-native-maps: ^0.8.2
react-native-cli: 1.0.0
react-native: 0.33.1

**Comment by WilliamPeralta** [comment]
i fix it adding this lines on gradle file 

```
compile "com.google.android.gms:play-services-base:+"
compile 'com.google.android.gms:play-services-location:+'
compile 'com.google.android.gms:play-services-maps:+'
```

is a bug???

**Comment by i8wu** [comment]
Hm, I believe this is caused by conflicting google-play-services stuff in different node_modules. I also got the error and fixed it with your change. My conflict is with [react-native-google-analytics-bridge](https://github.com/idehub/react-native-google-analytics-bridge), which has 
`compile 'com.google.android.gms:play-services-analytics:+'`

I thought the + shouldn't be causing issues, but I guess it does...any android experts know why?

**Comment by codyhazelwood** [comment]
I'm also having this issue, and I'm also using react-native-google-analytics-bridge.

Adding @WilliamPeralta's suggestions fixed it, but I too would like to understand it, since many of my RN libraries using native bindings seem to use google play services on Android.

**Comment by codesidekick** [comment]
I had a similar issue to this.

Following the instructions at http://stackoverflow.com/questions/31676045/cant-build-java-project-on-osx-yosemite/32729322#32729322 to remove all libraries inside `/Library/Java/Extensions` folder fixed it for me. It turns out the Australian governments AusKey system can cause react-native-maps to not be able to compile.

**Comment by kevmojay** [comment]
It seems to me that the problem can occur with any library you can find for react-native that use com.google.android.gms.

If you have references to com.google.android.gms in `android/app/build.gradle`.
Try giving the associated library a new version that you currently have installed.

I found the version number of the library I am using by navigating to `[YOUR_ANDROID_SDK]/extras/google/m2repository/com/google/android/gms`
Then find the library that might be causing you problems for example play-services-auth.

In there you will see all the versions. Apply the newest to your build.gradle.
`compile 'com.google.android.gms:play-services-auth:10.2.0'`

This worked for me when the above `:+` suggestions did not work.

**Comment by alvelig** [comment]
to #1773

**Comment by apurvaaggarwal** [comment]
update all library versions and gms version as well . It will definitely work. Make sure all google services library you are using must be of same version

**Comment by arapocket** [comment]
I think I have the most recent version of everything? I even tried 26.1.1 since I already have it installed same issue

<img width="743" alt="screen shot 2018-03-14 at 12 19 28 pm" src="https://user-images.githubusercontent.com/14900253/37425826-066ed20c-2782-11e8-8c1f-ebd8dbfce581.png">
