### ISSUE TITLE
App crashing Android/iOS

### ISSUE THREAD

**Issue by aamarcha** [react-community/react-native-maps#839]
Android: 6.0
iOS: 10.1.1
react-native: 0.34.0

here is the android stack :  

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                       at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
                                                       at android.view.View.<init>(View.java:3831)
                                                       at android.view.View.<init>(View.java:3945)
                                                       at android.view.ViewGroup.<init>(ViewGroup.java:599)
                                                       at android.view.ViewGroup.<init>(ViewGroup.java:595)
                                                       at android.view.ViewGroup.<init>(ViewGroup.java:591)
                                                       at android.view.ViewGroup.<init>(ViewGroup.java:587)
                                                       at android.widget.FrameLayout.<init>(FrameLayout.java:101)
                                                       at com.google.android.gms.maps.MapView.<init>(Unknown Source)
                                                       at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:84)
                                                       at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:72)
                                                       at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:28)
                                                       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$3.run(UIViewOperationQueue.java:807)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5782)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by mkjangid** [comment]
My app is also crashing and I am not getting any kind of logs.
Android : 6.0
React Native : 0.35.0
react-native-maps : 0.10.4
