### ISSUE TITLE
Instantly crashes app on run-android

### ISSUE THREAD

**Issue by pocesar** [react-community/react-native-maps#951]
Added no code, just linked this library and started the app

```
01-11 18:09:25.281  6288  6324 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
01-11 18:09:25.281  6288  6324 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.GoogleMapOptions
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:204)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:69)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:143)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:140)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:955)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:863)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-11 18:09:25.281  6288  6324 E AndroidRuntime:        ... 3 more
```

**Comment by monotv** [comment]
What fixed this for me:
- Update your Android SDK
- Put this in the dependencies block of your `android/app/build.gradle`:
```
  compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
  }
```
- Set these in your `android/app/build.gradle`:
```
   compileSdkVersion 23
   buildToolsVersion "23.0.3"
```

**Comment by pocesar** [comment]
```groovy
  compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
  }
  compile 'com.google.android.gms:play-services-base:+'
  compile 'com.google.android.gms:play-services-maps:+'
```

after tinkering with it, this one worked for me, thanks

**Comment by Nishchit14** [comment]
Found this helpful
https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by aaronbuchanan** [comment]
confirmed fixed for me, thanks for the background @Nishchit14!

**Comment by wardoost** [comment]
@pocesar fix worked for me 👍🏻

**Comment by RyanMitchellWilson** [comment]
Cannot get this to work with any version of play-services. I have tried every version from 8.4 to 11.4 and nothing works 100%. Sometimes I can load the map in android 7.0.0 but when I run the exact same build in 6.0.0 the app crashes as soon as I try to load the map. There are also versions which cause the build of my app to completely fail. Finally using the + sign doesn't work for any android version lower that 7.0.0. 

Has anyone found a version that actually works with multiple versions of android? Or at least must be compatible with 6 and 7

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by kgrajan12** [comment]
@pocesar  thanks this is worked for me too..
thank god..
