### ISSUE TITLE
work on ios, crash on android

### ISSUE THREAD

**Issue by niros001** [react-community/react-native-maps#998]
I do exactly the installation steps, the ios work fine and the android crash immediately without any error.
When i use this dependencies (version 9.0.0):
`apply plugin: 'com.google.gms.google-services'
    compile(project(':react-native-maps')){
           exclude group: 'com.google.android.gms', module: 'play-services-base'
           exclude group: 'com.google.android.gms', module: 'play-services-maps'
       }
       compile 'com.google.android.gms:play-services-base:9.0.0'
       compile 'com.google.android.gms:play-services-maps:9.0.0'` 
the app crash when i try open the map.
and when i use this dependencies (version 10.0.1):
`apply plugin: 'com.google.gms.google-services'
    compile(project(':react-native-maps')){
           exclude group: 'com.google.android.gms', module: 'play-services-base'
           exclude group: 'com.google.android.gms', module: 'play-services-maps'
       }
       compile 'com.google.android.gms:play-services-base:10.0.1'
       compile 'com.google.android.gms:play-services-maps:10.0.1'`

the app crash immediately on launch.

**Comment by spikebrehm** [comment]
What's the stack trace of the crash?

**Comment by jkomyno** [comment]
Same for me. Running ```react-native run-android``` throws no errors in terminal, however I capture this stacktrace with logcat:

> 02-09 15:33:49.988 4033-4033/com.airbnb.android.react.maps.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.airbnb.android.react.maps.example, PID: 4033
                                                                                     java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.airbnb.android.react.maps.example/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit
                                                                                         at java.lang.Runtime.load0(Runtime.java:908)
                                                                                         at java.lang.System.load(System.java:1505)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:65)
                                                                                         at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                                         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                                         at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                                         at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                                         at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                                                         at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                                         at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                                                         at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
                                                                                         at com.facebook.react.XReactInstanceManagerImpl.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:739)
                                                                                         at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundInner(XReactInstanceManagerImpl.java:399)
                                                                                         at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:370)
                                                                                         at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:215)
                                                                                         at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:110)
                                                                                         at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
                                                                                         at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                                         at android.app.Activity.performCreate(Activity.java:6679)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-09 15:33:49.989 1535-1626/system_process W/ActivityManager:   Force finishing activity com.airbnb.android.react.maps.example/.MainActivity
02-09 15:33:50.017 2201-2201/com.google.android.googlequicksearchbox:search W/SearchService: Abort, client detached.

So it most probably crashes due to "java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.airbnb.android.react.maps.example/lib-main/libgnustl_shared.so" is 32-bit instead of 64-bit".

## Environment
Windows 10
react-native 0.40
npm 4.0.3
Emulator: Nexus_5X_API_25 with Google Play Services.

Hope this will help solving this issue.

**Comment by jkomyno** [comment]
Any update on this one?

**Comment by jkomyno** [comment]
I have published a working project with the same exact examples as AirBnB here: https://github.com/jkomyno/react-native-maps-example
I'm gonna pull request it soon

**Comment by alvelig** [comment]
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by alvelig** [comment]
@jkomyno If you don't mind helping us please comment there: #1807
